displayName=Flipping Tables
author=cowbacca
support=https://github.com/Cowbacca/flipping-tables-plugin/issues
description=Plan Grand Exchange visits using current offers, selected inventory and portfolio advice
tags=grand exchange,flipping,portfolio
version=2.1.2
plugins=com.dashery.flippingtables.FlippingTablesPlugin
build=standard
